import { ReactNode } from 'react';
import type { Metadata } from 'next';

import '@/styles/globals.scss';

export const metadata: Metadata = {
    title: 'Read Journey',
    description: 'Generated by create next app',
    icons: {
        icon: '/favicon.ico',
    },
};

const RootLayout = ({ children }: { children: ReactNode }) => {
    return (
        <html lang="en">
            <body>{children}</body>
        </html>
    );
};

export default RootLayout;
